In [74]:
import SVMc
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [75]:
diabetes_data = pd.read_csv('diabetes.csv')

In [76]:
diabetes_data.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [77]:
diabetes_data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [78]:
diabetes_data.shape

(768, 9)

In [79]:
diabetes_data.describe()

       Pregnancies     Glucose  ...         Age     Outcome
count   768.000000  768.000000  ...  768.000000  768.000000
mean      3.845052  120.894531  ...   33.240885    0.348958
std       3.369578   31.972618  ...   11.760232    0.476951
min       0.000000    0.000000  ...   21.000000    0.000000
25%       1.000000   99.000000  ...   24.000000    0.000000
50%       3.000000  117.000000  ...   29.000000    0.000000
75%       6.000000  140.250000  ...   41.000000    1.000000
max      17.000000  199.000000  ...   81.000000    1.000000

[8 rows x 9 columns]

In [80]:
diabetes_data['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

0 - Non-diabetic
1 - Diabetic

In [81]:
X = diabetes_data.drop('Outcome', axis = 1)
Y = diabetes_data['Outcome']

In [82]:
cols = ['Glucose', 'BloodPressure', 'SkinThickness',
        'Insulin', 'BMI']

for col in cols:
    X[col] = X[col].replace(0, X[col].median())

In [83]:
scaler = StandardScaler()

In [84]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, stratify = Y, random_state = 2)

In [85]:
print(X_train, X_test)

     Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
619            0      119             72  ...  32.4                     0.141   24
329            6      105             70  ...  30.8                     0.122   37
13             1      189             60  ...  30.1                     0.398   59
476            2      105             80  ...  33.7                     0.711   29
45             0      180             66  ...  42.0                     1.893   25
..           ...      ...            ...  ...   ...                       ...  ...
303            5      115             98  ...  52.9                     0.209   28
592            3      132             80  ...  34.4                     0.402   44
559           11       85             74  ...  30.1                     0.300   35
725            4      112             78  ...  39.4                     0.236   38
253            0       86             68  ...  35.8                     0.238   25

[614 rows x 8 columns]      Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
615            3      106             72  ...  25.8                     0.207   27
80             3      113             44  ...  22.4                     0.140   22
148            5      147             78  ...  33.7                     0.218   65
132            3      170             64  ...  34.5                     0.356   30
501            3       84             72  ...  37.2                     0.267   28
..           ...      ...            ...  ...   ...                       ...  ...
127            1      118             58  ...  33.3                     0.261   23
185            7      194             68  ...  35.9                     0.745   41
85             2      110             74  ...  32.4                     0.698   27
497            2       81             72  ...  30.1                     0.547   25
86            13      106             72  ...  36.6                     0.178   45

[154 rows x 8 columns]

In [86]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [87]:
print(X_train, X_test)

[[-1.13796489 -0.10144145 -0.06381849 ... -0.03489907 -0.98159708
  -0.7885233 ]
 [ 0.64067858 -0.55941977 -0.22641    ... -0.26453633 -1.03823795
   0.31879426]
 [-0.84152431  2.18845013 -1.03936754 ... -0.36500264 -0.21545477
   2.19271628]
 ...
 [ 2.12288146 -1.2136745   0.09877302 ... -0.36500264 -0.50760242
   0.14843771]
 [ 0.04779742 -0.33043061  0.42395603 ...  0.96976397 -0.69839272
   0.40397253]
 [-1.13796489 -1.18096177 -0.38900151 ...  0.45308012 -0.69243053
  -0.70334503]] [[-0.24864315 -0.52670703 -0.06381849 ... -0.98215279 -0.78484458
  -0.53298848]
 [-0.24864315 -0.29771787 -2.3400996  ... -1.47013197 -0.98457818
  -0.95887985]
 [ 0.344238    0.81451518  0.42395603 ...  0.15168121 -0.7520525
   2.70378593]
 ...
 [-0.54508373 -0.39585608  0.09877302 ... -0.03489907  0.67887478
  -0.53298848]
 [-0.54508373 -1.34452545 -0.06381849 ... -0.36500264  0.22872891
  -0.70334503]
 [ 2.71576261 -0.52670703 -0.06381849 ...  0.56789875 -0.87129644
   1.00022045]]

In [88]:
model = SVMc.Support_Vector_Machine(learning_rate = 0.001, iterations = 1000, lambda_param = 0.01)

In [89]:
model.fit(X_train, Y_train)

In [90]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(Y_train, X_train_prediction)
print(f'Accuracy score on training data ={training_data_accuracy * 100:.2f}% ')

Accuracy score on training data =34.85%